/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK;

import Aspose.OCR.Cloud.SDK.ApiException;
import java.io.File;
import Aspose.OCR.Cloud.SDK.model.OCRResponse;
import Aspose.OCR.Cloud.SDK.model.ProblemDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImageProcessingApi
 */
@Disabled
public class ImageProcessingApiTest {

    private final ImageProcessingApi api = new ImageProcessingApi();

    /**
     * GetResultFile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResultFileTest() throws ApiException {
        String id = null;
        Object response = api.getResultFile(id);
        // TODO: test validations
    }

    /**
     * GetResultTask
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResultTaskTest() throws ApiException {
        String id = null;
        OCRResponse response = api.getResultTask(id);
        // TODO: test validations
    }

    /**
     * PostBinarizationFile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postBinarizationFileTest() throws ApiException {
        File _file = null;
        String response = api.postBinarizationFile(_file);
        // TODO: test validations
    }

    /**
     * PostDewarpingFile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postDewarpingFileTest() throws ApiException {
        File _file = null;
        String response = api.postDewarpingFile(_file);
        // TODO: test validations
    }

    /**
     * PostSkewCorrectionFile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postSkewCorrectionFileTest() throws ApiException {
        File _file = null;
        String response = api.postSkewCorrectionFile(_file);
        // TODO: test validations
    }

    /**
     * PostUpsamplingImageFile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postUpsamplingFileTest() throws ApiException {
        File _file = null;
        String response = api.postUpsamplingFile(_file);
        // TODO: test validations
    }

}
