/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK;

import Aspose.OCR.Cloud.SDK.ApiException;
import Aspose.OCR.Cloud.SDK.model.OCRRecognizeImageBody;
import Aspose.OCR.Cloud.SDK.model.OCRResponse;
import Aspose.OCR.Cloud.SDK.model.ProblemDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecognizeImageApi
 */
@Disabled
public class RecognizeImageApiTest {

    private final RecognizeImageApi api = new RecognizeImageApi();

    /**
     * CancelRecognizeImage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelRecognizeImageTest() throws ApiException {
        String id = null;
        api.cancelRecognizeImage(id);
        // TODO: test validations
    }

    /**
     * GetRecognizeImage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRecognizeImageTest() throws ApiException {
        String id = null;
        OCRResponse response = api.getRecognizeImage(id);
        // TODO: test validations
    }

    /**
     * PostRecognizeImage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postRecognizeImageTest() throws ApiException {
        OCRRecognizeImageBody ocRRecognizeImageBody = null;
        String response = api.postRecognizeImage(ocRRecognizeImageBody);
        // TODO: test validations
    }

}
