/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK;

import Aspose.OCR.Cloud.SDK.ApiException;
import Aspose.OCR.Cloud.SDK.model.OCRRecognizePdfBody;
import Aspose.OCR.Cloud.SDK.model.OCRResponse;
import Aspose.OCR.Cloud.SDK.model.ProblemDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecognizePdfApi
 */
@Disabled
public class RecognizePdfApiTest {

    private final RecognizePdfApi api = new RecognizePdfApi();

    /**
     * CancelRecognizePdf
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelRecognizePdfTest() throws ApiException {
        String id = null;
        api.cancelRecognizePdf(id);
        // TODO: test validations
    }

    /**
     * GetRecognizePdf
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRecognizePdfTest() throws ApiException {
        String id = null;
        OCRResponse response = api.getRecognizePdf(id);
        // TODO: test validations
    }

    /**
     * PostRecognizePdf
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postRecognizePdfTest() throws ApiException {
        OCRRecognizePdfBody ocRRecognizePdfBody = null;
        String response = api.postRecognizePdf(ocRRecognizePdfBody);
        // TODO: test validations
    }

}
