/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK;

import Aspose.OCR.Cloud.SDK.ApiException;
import Aspose.OCR.Cloud.SDK.model.OCRRecognizeReceiptBody;
import Aspose.OCR.Cloud.SDK.model.OCRResponse;
import Aspose.OCR.Cloud.SDK.model.ProblemDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecognizeReceiptApi
 */
@Disabled
public class RecognizeReceiptApiTest {

    private final RecognizeReceiptApi api = new RecognizeReceiptApi();

    /**
     * CancelRecognizeReceipt
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelRecognizeReceiptTest() throws ApiException {
        String id = null;
        api.cancelRecognizeReceipt(id);
        // TODO: test validations
    }

    /**
     * GetRecognizeReceipt
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRecognizeReceiptTest() throws ApiException {
        String id = null;
        OCRResponse response = api.getRecognizeReceipt(id);
        // TODO: test validations
    }

    /**
     * PostRecognizeReceipt
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postRecognizeReceiptTest() throws ApiException {
        OCRRecognizeReceiptBody ocRRecognizeReceiptBody = null;
        String response = api.postRecognizeReceipt(ocRRecognizeReceiptBody);
        // TODO: test validations
    }

}
