/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK;

import Aspose.OCR.Cloud.SDK.ApiException;
import Aspose.OCR.Cloud.SDK.model.OCRRecognizeTableBody;
import Aspose.OCR.Cloud.SDK.model.OCRResponse;
import Aspose.OCR.Cloud.SDK.model.ProblemDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecognizeTableApi
 */
@Disabled
public class RecognizeTableApiTest {

    private final RecognizeTableApi api = new RecognizeTableApi();

    /**
     * CancelRecognizeTable
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelRecognizeTableTest() throws ApiException {
        String id = null;
        api.cancelRecognizeTable(id);
        // TODO: test validations
    }

    /**
     * GetRecognizeTable
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRecognizeTableTest() throws ApiException {
        String id = null;
        OCRResponse response = api.getRecognizeTable(id);
        // TODO: test validations
    }

    /**
     * PostRecognizeTable
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postRecognizeTableTest() throws ApiException {
        OCRRecognizeTableBody ocRRecognizeTableBody = null;
        String response = api.postRecognizeTable(ocRRecognizeTableBody);
        // TODO: test validations
    }

}
