/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK;

import Aspose.OCR.Cloud.SDK.ApiException;
import Aspose.OCR.Cloud.SDK.model.ProblemDetails;
import Aspose.OCR.Cloud.SDK.model.TTSBody;
import Aspose.OCR.Cloud.SDK.model.TTSResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TextToSpeechApi
 */
@Disabled
public class TextToSpeechApiTest {

    private final TextToSpeechApi api = new TextToSpeechApi();

    /**
     * GetTextToSpeechResult
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTextToSpeechResultTest() throws ApiException {
        String id = null;
        TTSResponse response = api.getTextToSpeechResult(id);
        // TODO: test validations
    }

    /**
     * GetTextToSpeechResultFile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTextToSpeechResultFileTest() throws ApiException {
        String id = null;
        Object response = api.getTextToSpeechResultFile(id);
        // TODO: test validations
    }

    /**
     * PostTextToSpeech
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postTextToSpeechTest() throws ApiException {
        TTSBody ttSBody = null;
        String response = api.postTextToSpeech(ttSBody);
        // TODO: test validations
    }

}
