/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OCRRect
 */
public class OCRRectTest {
    private final OCRRect model = new OCRRect();

    /**
     * Model tests for OCRRect
     */
    @Test
    public void testOCRRect() {
        // TODO: test OCRRect
    }

    /**
     * Test the property 'topLeftX'
     */
    @Test
    public void topLeftXTest() {
        // TODO: test topLeftX
    }

    /**
     * Test the property 'topLeftY'
     */
    @Test
    public void topLeftYTest() {
        // TODO: test topLeftY
    }

    /**
     * Test the property 'bottomRightX'
     */
    @Test
    public void bottomRightXTest() {
        // TODO: test bottomRightX
    }

    /**
     * Test the property 'bottomRightY'
     */
    @Test
    public void bottomRightYTest() {
        // TODO: test bottomRightY
    }

}
