/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK.model;

import Aspose.OCR.Cloud.SDK.model.OCRRect;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OCRRegion
 */
public class OCRRegionTest {
    private final OCRRegion model = new OCRRegion();

    /**
     * Model tests for OCRRegion
     */
    @Test
    public void testOCRRegion() {
        // TODO: test OCRRegion
    }

    /**
     * Test the property 'rect'
     */
    @Test
    public void rectTest() {
        // TODO: test rect
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

}
