/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK.model;

import Aspose.OCR.Cloud.SDK.model.DsrConfidence;
import Aspose.OCR.Cloud.SDK.model.DsrMode;
import Aspose.OCR.Cloud.SDK.model.Language;
import Aspose.OCR.Cloud.SDK.model.OCRRegion;
import Aspose.OCR.Cloud.SDK.model.ResultType;
import Aspose.OCR.Cloud.SDK.model.ResultTypeTable;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OCRSettingsRecognizeReceipt
 */
public class OCRSettingsRecognizeReceiptTest {
    private final OCRSettingsRecognizeReceipt model = new OCRSettingsRecognizeReceipt();

    /**
     * Model tests for OCRSettingsRecognizeReceipt
     */
    @Test
    public void testOCRSettingsRecognizeReceipt() {
        // TODO: test OCRSettingsRecognizeReceipt
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'makeSkewCorrect'
     */
    @Test
    public void makeSkewCorrectTest() {
        // TODO: test makeSkewCorrect
    }

    /**
     * Test the property 'makeSpellCheck'
     */
    @Test
    public void makeSpellCheckTest() {
        // TODO: test makeSpellCheck
    }

    /**
     * Test the property 'makeContrastCorrection'
     */
    @Test
    public void makeContrastCorrectionTest() {
        // TODO: test makeContrastCorrection
    }

    /**
     * Test the property 'makeBinarization'
     */
    @Test
    public void makeBinarizationTest() {
        // TODO: test makeBinarization
    }

    /**
     * Test the property 'makeUpsampling'
     */
    @Test
    public void makeUpsamplingTest() {
        // TODO: test makeUpsampling
    }

    /**
     * Test the property 'dsrMode'
     */
    @Test
    public void dsrModeTest() {
        // TODO: test dsrMode
    }

    /**
     * Test the property 'dsrConfidence'
     */
    @Test
    public void dsrConfidenceTest() {
        // TODO: test dsrConfidence
    }

    /**
     * Test the property 'resultType'
     */
    @Test
    public void resultTypeTest() {
        // TODO: test resultType
    }

    /**
     * Test the property 'resultTypeTable'
     */
    @Test
    public void resultTypeTableTest() {
        // TODO: test resultTypeTable
    }

    /**
     * Test the property 'regions'
     */
    @Test
    public void regionsTest() {
        // TODO: test regions
    }

}
