/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK.model;

import Aspose.OCR.Cloud.SDK.model.LanguageTTS;
import Aspose.OCR.Cloud.SDK.model.ResultTypeTTS;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TTSBody
 */
public class TTSBodyTest {
    private final TTSBody model = new TTSBody();

    /**
     * Model tests for TTSBody
     */
    @Test
    public void testTTSBody() {
        // TODO: test TTSBody
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'resultType'
     */
    @Test
    public void resultTypeTest() {
        // TODO: test resultType
    }

}
