/*
 * Aspose OCR Cloud 5.0 API
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Aspose.OCR.Cloud.SDK.model;

import Aspose.OCR.Cloud.SDK.model.ResponseStatusCode;
import Aspose.OCR.Cloud.SDK.model.TTSError;
import Aspose.OCR.Cloud.SDK.model.TTSResult;
import Aspose.OCR.Cloud.SDK.model.TTSTaskStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TTSResponse
 */
public class TTSResponseTest {
    private final TTSResponse model = new TTSResponse();

    /**
     * Model tests for TTSResponse
     */
    @Test
    public void testTTSResponse() {
        // TODO: test TTSResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'responseStatusCode'
     */
    @Test
    public void responseStatusCodeTest() {
        // TODO: test responseStatusCode
    }

    /**
     * Test the property 'taskStatus'
     */
    @Test
    public void taskStatusTest() {
        // TODO: test taskStatus
    }

    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
